/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mytheclipse.modul4;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author asephs
 */
public class Modul4 extends javax.swing.JFrame {

    /**
     * Creates new form Modul4
     */
    public Modul4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Bangun Datar");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem1.setText("Segitiga");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem2.setText("Persegi");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem3.setText("Lingkaran");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Bangun Ruang");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem4.setText("Kubus");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem5.setText("Balok");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem6.setText("Lingkaran");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new FormSegitiga().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new FormPersegi().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new FormLingkaran().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new FormKubus().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new FormBalok().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new FormLingkaranRuang().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modul4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables

    public class FormSegitiga extends JFrame {
        public FormSegitiga() {
            setTitle("Form Segitiga");
            setSize(300, 200);
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            setLocationRelativeTo(null);

            JLabel labelBase = new JLabel("Alas:");
            JLabel labelHeight = new JLabel("Tinggi:");
            JTextField textBase = new JTextField(5);
            JTextField textHeight = new JTextField(5);
            JButton buttonCalculate = new JButton("Hitung Luas");
            JLabel labelResult = new JLabel("Hasil:");

            buttonCalculate.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    try {
                        double base = Double.parseDouble(textBase.getText());
                        double height = Double.parseDouble(textHeight.getText());
                        double area = 0.5 * base * height;
                        labelResult.setText("Hasil: " + area);
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Masukkan angka yang valid");
                    }
                }
            });

            setLayout(new java.awt.FlowLayout());
            add(labelBase);
            add(textBase);
            add(labelHeight);
            add(textHeight);
            add(buttonCalculate);
            add(labelResult);
        }
    }

    public class FormPersegi extends JFrame {
        public FormPersegi() {
            setTitle("Form Persegi");
            setSize(300, 200);
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            setLocationRelativeTo(null);

            JLabel labelSide = new JLabel("Sisi:");
            JTextField textSide = new JTextField(5);
            JButton buttonCalculate = new JButton("Hitung Luas");
            JLabel labelResult = new JLabel("Hasil:");

            buttonCalculate.addActionListener(new ActionListener() {
                public void actionPerformed (ActionEvent e) {
                    try {
                        double side = Double.parseDouble(textSide.getText());
                        double area = side * side;
                        labelResult.setText("Hasil: " + area);
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Masukkan angka yang valid");
                    }
                }
            });

            setLayout(new java.awt.FlowLayout());
            add(labelSide);
            add(textSide);
            add(buttonCalculate);
            add(labelResult);
        }
    }

    public class FormLingkaran extends JFrame {
        public FormLingkaran() {
            setTitle("Form Lingkaran");
            setSize(300, 200);
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            setLocationRelativeTo(null);

            JLabel labelRadius = new JLabel("Jari-jari:");
            JTextField textRadius = new JTextField(5);
            JButton buttonCalculate = new JButton("Hitung Luas");
            JLabel labelResult = new JLabel("Hasil:");

            buttonCalculate.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    try {
                        double radius = Double.parseDouble(textRadius.getText());
                        double area = Math.PI * radius * radius;
                        labelResult.setText("Hasil: " + area);
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Masukkan angka yang valid");
                    }
                }
            });

            setLayout(new java.awt.FlowLayout());
            add(labelRadius);
            add(textRadius);
            add(buttonCalculate);
            add(labelResult);
        }
    }

    public class FormKubus extends JFrame {
        public FormKubus() {
            setTitle("Form Kubus");
            setSize(300, 200);
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            setLocationRelativeTo(null);

            JLabel labelSide = new JLabel("Sisi:");
            JTextField textSide = new JTextField(5);
            JButton buttonCalculate = new JButton("Hitung Volume");
            JLabel labelResult = new JLabel("Hasil:");

            buttonCalculate.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    try {
                        double side = Double.parseDouble(textSide.getText());
                        double volume = Math.pow(side, 3);
                        labelResult.setText("Hasil: " + volume);
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Masukkan angka yang valid");
                    }
                }
            });

            setLayout(new java.awt.FlowLayout());
            add(labelSide);
            add(textSide);
            add(buttonCalculate);
            add(labelResult);
        }
    }

    public class FormBalok extends JFrame {
        public FormBalok() {
            setTitle("Form Balok");
            setSize(300, 200);
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            setLocationRelativeTo(null);

            JLabel labelLength = new JLabel("Panjang:");
            JLabel labelWidth = new JLabel("Lebar:");
            JLabel labelHeight = new JLabel("Tinggi:");
            JTextField textLength = new JTextField(5);
            JTextField textWidth = new JTextField(5);
            JTextField textHeight = new JTextField(5);
            JButton buttonCalculate = new JButton("Hitung Volume");
            JLabel labelResult = new JLabel("Hasil:");

            buttonCalculate.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    try {
                        double length = Double.parseDouble(textLength.getText());
                        double width = Double.parseDouble(textWidth.getText());
                        double height = Double.parseDouble(textHeight.getText());
                        double volume = length * width * height;
                        labelResult.setText("Hasil: " + volume);
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Masukkan angka yang valid");
                    }
                }
            });

            setLayout(new java.awt.FlowLayout());
            add(labelLength);
            add(textLength);
            add(labelWidth);
            add(textWidth);
            add(labelHeight);
            add(textHeight);
            add(buttonCalculate);
            add(labelResult);
        }
    }

    public class FormLingkaranRuang extends JFrame {
        public FormLingkaranRuang() {
            setTitle("Form Lingkaran (Bangun Ruang)");
            setSize(300, 200);
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            setLocationRelativeTo(null);

            JLabel labelRadius = new JLabel("Jari-jari:");
            JTextField textRadius = new JTextField(5);
            JButton buttonCalculate = new JButton("Hitung Volume");
            JLabel labelResult = new JLabel("Hasil:");

            buttonCalculate.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    try {
                        double radius = Double.parseDouble(textRadius.getText());
                        double volume = (4.0 / 3.0) * Math.PI * Math.pow(radius, 3);
                        labelResult.setText("Hasil: " + volume);
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Masukkan angka yang valid");
                    }
                }
            });

            setLayout(new java.awt.FlowLayout());
            add(labelRadius);
            add(textRadius);
            add(buttonCalculate);
            add(labelResult);
        }
    }
}
