name: Build Maven Module 3

on:
  push:
    paths:
      - 'modul3/modul3/**'
  pull_request:
    paths:
      - 'modul3/modul3/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Setup Java JDK
      uses: actions/setup-java@v4.5.0
      with:
        distribution: 'temurin' # Specify the distribution
        java-version: '21' # Specify the latest Java version

    - name: Build with Maven
      run: mvn -f modul3/modul3/pom.xml clean install
