name: Build Maven Module 3

on:
  push:
    paths:
      - 'modul3/modul3/**'
  pull_request:
    paths:
      - 'modul3/modul3/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # Specify the distribution
        java-version: '21'

    - name: Build with Maven
      run: mvn -f modul3/modul3/pom.xml clean install
